### ISSUE TITLE
Command to play not working

### ISSUE THREAD

**Issue by glmeyer** [barnybug/go-cast#11]
I installed go-cast on my Mac but when I try to play it prompts by saying no help topic for play. Here is the play command I am using.

Garys-MacBook-Pro:bin garymeyer$ cast --host=192.168.85.48 --port=42662 play http://audiocdn.mainstreaming.tv/101156/mmc
No help topic for 'play'

**Comment by barnybug** [comment]
The command is 'media play' see usage: https://github.com/barnybug/go-cast#usage
