### ISSUE TITLE
Error with using hostname

### ISSUE THREAD

**Issue by glmeyer** [barnybug/go-cast#14]
I have been using go-cast for a few weeks now and have found that the DHCP changes the ip address. I have addressed this issue with the physical speakers by reserving the ip address, but I am not able to reserve the ip for the Chromecast groups. So I have been trying to use the --name= option in place of the  --host= option, and I am getting the following error output. 

Command with --host and no error:

root@opendns:/usr/local/bin# sudo /usr/local/bin/cast --host=192.168.85.48 --port=42626 media play http://audiocdn.mainstreaming.tv/101156/mmc
Connecting to 192.168.85.48:42626...
Connected

The command with --name= and error:

root@opendns:/usr/local/bin# sudo /usr/local/bin/cast --name=Upstairs --port=42626 media play http://audiocdn.mainstreaming.tv/101156/mmc
Connecting to 192.168.85.48:42626...
Connected
2018/11/21 07:46:06.686064 [INFO] mdns: Closing client {0x11878410 0x11878418 0x11878420 0x11878428 true 0x11882280 {1 0}}
2018/11/21 07:46:06.686877 [ERR] mdns: Failed to read packet: read udp4 0.0.0.0:59740: use of closed network connection
2018/11/21 07:46:06.687015 [ERR] mdns: Failed to read packet: read udp6 [::]:49238: use of closed network connection
2018/11/21 07:46:06.687140 [ERR] mdns: Failed to read packet: read udp4 0.0.0.0:5353: use of closed network connection
2018/11/21 07:46:06.687262 [ERR] mdns: Failed to read packet: read udp6 [::]:5353: use of closed network connection

Note: Despite getting the error the music still casts out to the speakers in the group. I am using the 0.1.0 cast-linux-arm release on a raspberry pi.

**Comment by barnybug** [comment]
Hi, you can safely ignore those spurious error messages - they come from one of the libraries go-cast uses which I haven't control over.
