### ISSUE TITLE
Support streaming local device, like microphone in / aux in?

### ISSUE THREAD

**Issue by dmurph** [barnybug/go-cast#5]
Hi!

I would love to be able to 'cast' audio from a line in. I want to try to get this working - do you have any ideas on how I could hook this up? Where is the binary data sent from the audio files currently?

**Comment by barnybug** [comment]
Hey - you could potentially do this - you'd need a webserver serving up an audio stream of the data on an http url, and then you can start the cast playing from this by doing `cast --name Chromecast media play http://streamurl/`. It'd play wav, mp3, etc.

As to serving up a microphone as a stream - fmpeg/ffserver might be able to (not tested):
https://ubuntuforums.org/showthread.php?t=1544946

**Comment by TonyApuzzo** [comment]
There are many ways to do this using a PC as an intermediary.  

* https://github.com/acidhax/chromecast-audio-stream/
* https://www.addictivetips.com/windows-tips/how-to-stream-audio-from-your-pc-or-mac-to-chromecast/
* BubbleUPNP can create a DLNA endpoint on your PC (or Android) that can forward to the Chromecast Audio and you can use that to direct a microphone to your chromecast.
* On Linux there is a configuration for pulseaudio to do it as well, but I've not done it.
* As far as forwarding a recording from the line-in or mic input on your PC you should be able to do that once you get the PC's audio streaming to the the Chromecast.  Then set the microphone/input properties to "listen" in control panel.  On my Windows 10 it is Settings > Sound > Input > Device Properties > Listen > Check the "Listen to this device" button.

**Comment by dmurph** [comment]
Interesting... I'm basically working with a line-in aux cable, and I currently have a couple different Raspberry Pi's (and a macbook if I need) to work with.

I'll look into hosting the ffmpeg server, otherwise it looks like maybe I could hook up to the input device in alsa?

**Comment by TonyApuzzo** [comment]
Yeah, for RPi you can use http://mkchromecast.com/ and Alsa but you'll need a USB soundcard that has an input since the basic RPi hardware doesn't have audio-in.  There are lots of options but nothing is a perfectly simple solution AFAIK.

**Comment by dmurph** [comment]
Hm - I'm going to try to use https://fe-pi.com/products/fe-pi-audio-z-v2

**Comment by barnybug** [comment]
mkchromecast seems like overkill (python + node.js + ...!) given it's just running ffmpeg underneath. Run ffmpeg, and the cast command above. 1 binary solution for the pi :-)
