### ISSUE TITLE
cast does not accept --name option

### ISSUE THREAD

**Issue by rexxmundi** [barnybug/go-cast#6]
$ cast --version
cast version 0.0.5

On the examples presented on the main page, global option "--name" is used however version 0.0.5 downloaded from latest does not accept the option.  Output returned:

$ cast --name patio quit
Incorrect Usage.

NAME:
   cast - Command line tool for the Chromecast

USAGE:
   cast [global options] command [command options] [arguments...]
   
VERSION:
   0.0.5

**Comment by barnybug** [comment]
Thanks for highlighting this. It's been a while since a release binary was built - I'll get it building again and release the latest master.

**Comment by barnybug** [comment]
Try: https://github.com/barnybug/go-cast/releases/tag/0.1.0

**Comment by rexxmundi** [comment]
Yep that fixed it.  Thanks for you help.
