### ISSUE TITLE
url command points to broken page

### ISSUE THREAD

**Issue by axlroden** [barnybug/go-cast#7]
Seems like the url command is pointing to a github page that doesn't exist anymore for the app I'm assuming.

**Comment by barnybug** [comment]
Not sure what you mean - could you elaborate?

**Comment by axlroden** [comment]
when I run the url command to chromecast, chromecast ends up on a 404 on github, presumably the app it was supposed to run.

**Comment by barnybug** [comment]
I don't think it worked 100% reliably. Apps aren't page so there's not a github page it loads, so weird you're seeing this.

**Comment by axlroden** [comment]
From what I recall, I've tried other URL loading apps, where it then uses a github website to kinda proxy the actual website, what "service" did you use for this?

**Comment by jwallet** [comment]
i see the same page as well when using `url load`

**Comment by barnybug** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
