### ISSUE TITLE
casting .ts file

### ISSUE THREAD

**Issue by jwallet** [barnybug/go-cast#9]
hey I want to thank you for this amazing library first.
and a quick question, do you think it may be possible to transfer directly a ts file from `url load` to the chromecast or i will have to edit this project for my need to transcode the ts file in golang to mp4

edit: a bit more info, i'm using streamlink to get a m3u8 file from the web and i host the feed using that same tool, it goes to `127.0.0.1:any` and then it waits for clients. so i can't give a link to go-cast including the extension.

**Comment by barnybug** [comment]
I don't think chrome casts can play .ts files, here is the list of supported video formats:
https://developers.google.com/cast/docs/mpl_streaming_protocols
